### ISSUE TITLE
Issue with `poa build 4`

### ISSUE THREAD

**Issue by ShatilKhan** [hashgraph/hedera-theft-prevention-demo#56]
### Description

I'm having this issue with proof-of-action build 4 while trying to run `docker-compose build`
```shell
 => ERROR [poa build 4/9] RUN cd /opt/hedera-proof-of-action && ./gradlew --no-daemon                                                                                0.3s 
------
 > [poa build 4/9] RUN cd /opt/hedera-proof-of-action && ./gradlew --no-daemon:
0.292 /usr/bin/env: ‘sh\r’: No such file or directory
------
failed to solve: process "/bin/sh -c cd /opt/hedera-proof-of-action && ./gradlew --no-daemon" did not complete successfully: exit code: 127
``` 

I changed these values, but didn't update `TOPIC_ID=` as I need to run the program first to produce a topic ID I believe
```shell
HEDERA_OPERATOR_ID=0.0.xxx
HEDERA_OPERATOR_KEY=302e....
```

### Steps to reproduce

Run `docker-compose build`

### Hedera network

testnet

### Version

Docker version 24.0.7, build afdd53b

### Operating system

Windows

**Comment by gregscullard** [comment]
Hi, thanks for reporting this, I've updated the demo so it's more up to date with recent changes to the SDK + node version, could you pull the latest version and try again, then close the issue if all is well ?

Many thanks

**Comment by ShatilKhan** [comment]
Thanks for updating
unfortunately I'm still receiving the same error. Could this be an internal system issue with my pc?
```bash
=> ERROR [poa build 4/9] RUN cd /opt/hedera-proof-of-action && ./gradlew --no-daemon
 1.1s
------
 > [poa build 4/9] RUN cd /opt/hedera-proof-of-action && ./gradlew --no-daemon:
1.075 /usr/bin/env: ‘sh\r’: No such file or directory
------
failed to solve: process "/bin/sh -c cd /opt/hedera-proof-of-action && ./gradlew --no-daemon" did not complete successfully: exit code: 127
``` 
My Node Version : 18

**Comment by ShatilKhan** [comment]
Closing the issue as the solution has been provided, it would be convenient to add this to the readme file @gregscullard , so that others don't face the same issue
I do have some problems with finding the topic id, but I'm going to open up a new issue to discuss it.
